AWSTemplateFormatVersion: '2010-09-09'
Description: Top-level stack template that deploys a nested stack

Resources:
######## NETWORKING NESTED STACKS FOR EC2
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: components/network.yaml
      Parameters:
        PublicInstance: 'Yes'

####### EC2 NESTED STACKS
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: components/ec2.yaml
      TimeoutInMinutes: 30
      Parameters:
        SubnetId: !Select [0, !Ref NetworkStack.Outputs.SubnetIds]
        SecurityGroupId: !Ref NetworkStack.Outputs.SecurityGroupId
        InstanceType: t2.micro
        InstanceOS: Linux

######## LOAD BALANCER NESTED STACKS
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: components/loadbalancer.yaml
      TimeoutInMinutes: 30
      Parameters:
        VPCId: !Ref NetworkStack.Outputs.VPCId
        SubnetIds: !Ref NetworkStack.Outputs.SubnetIds
        InstanceId1: !Ref EC2Stack.Outputs.InstanceId
        AllowedIPs: '192.0.2.44/32,10.0.0.0/8'


Outputs:
  SSHKeyParameter:
    Description: SSM Parameter with SSH Key content
    Value: !Ref EC2Stack.Outputs.KeySSMParameter